version: "3.9"
services:
  kitchenware-model:
    image: kitchenware-model:xception_v2
  gateway:
    image: kitchenware-gateway-webapp:v1
    environment:
      - TF_SERVING_HOST=kitchenware-model:8500
    ports:
      - "6969:6969"